service: default
runtime: python39
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 3.9
env: standard
network:
  name: palm-network
vpc_access_connector:
 name: projects/gen-genai-explorers-team/locations/us-central1/connectors/palm-connector-2
